### ISSUE TITLE
LDtk Render Tile issue

### ISSUE THREAD

**Issue by LeHaine** [LeHaine/kiwi#1]
Weird bug when have a tiled layer and then decreasing the level size by pulling one of the sides down over existing tiles and then try to render LDtk level.

**Comment by LeHaine** [comment]
```Java
java.lang.IndexOutOfBoundsException
	at java.base/java.nio.Buffer.checkIndex(Buffer.java:722)
	at java.base/java.nio.HeapByteBuffer.putFloat(HeapByteBuffer.java:562)
	at com.soywiz.korge.render.TexturedVertexArray.quadV(BatchBuilder2D.kt:1043)
	at com.soywiz.korge.render.TexturedVertexArray.quadV-sZ_2uj8(BatchBuilder2D.kt:879)
	at com.soywiz.korge.render.TexturedVertexArray.quadV-sZ_2uj8(BatchBuilder2D.kt:892)
	at com.lehaine.kiwi.korge.view.ldtk.LDtkLayerView.renderTile-hNYR2zc(LDtkLayerView.kt:288)
	at com.lehaine.kiwi.korge.view.ldtk.LDtkLayerView.computeVertexIfRequired(LDtkLayerView.kt:179)
	at com.lehaine.kiwi.korge.view.ldtk.LDtkLayerView.renderInternal(LDtkLayerView.kt:67)
	at com.soywiz.korge.view.View.render(View.kt:706)
	at com.soywiz.korge.view.Container.renderInternal(Container.kt:208)
	at com.soywiz.korge.view.View.render(View.kt:706)
	at com.soywiz.korge.view.Container.renderInternal(Container.kt:208)
	at com.soywiz.korge.view.FixedSizeContainer.renderInternal(FixedSizeContainer.kt:49)
	at com.soywiz.korge.view.View.render(View.kt:706)
	at com.soywiz.korge.view.Container.renderInternal(Container.kt:208)
	at com.soywiz.korge.view.View.render(View.kt:706)
	at com.soywiz.korge.view.Container.renderInternal(Container.kt:208)
	at com.soywiz.korge.view.FixedSizeContainer.renderInternal(FixedSizeContainer.kt:46)
	at com.soywiz.korge.view.View.render(View.kt:706)
	at com.soywiz.korge.view.Container.renderInternal(Container.kt:208)
	at com.soywiz.korge.view.View.render(View.kt:706)
	at com.soywiz.korge.view.Container.renderInternal(Container.kt:208)
	at com.soywiz.korge.view.View.render(View.kt:706)
	at com.soywiz.korge.scene.TransitionKt$AlphaTransition$1.invoke(Transition.kt:67)
	at com.soywiz.korge.scene.TransitionKt$AlphaTransition$1.invoke(Transition.kt)
	at com.soywiz.korge.scene.TransitionKt$withEasing$1.invoke(Transition.kt:56)
	at com.soywiz.korge.scene.TransitionKt$withEasing$1.invoke(Transition.kt)
	at com.soywiz.korge.scene.TransitionView.renderInternal(Transition.kt:46)
	at com.soywiz.korge.view.View.render(View.kt:706)
	at com.soywiz.korge.view.Container.renderInternal(Container.kt:208)
	at com.soywiz.korge.view.View.render(View.kt:706)
	at com.soywiz.korge.view.Container.renderInternal(Container.kt:208)
	at com.soywiz.korge.view.Stage.renderInternal(Stage.kt:48)
	at com.soywiz.korge.view.View.render(View.kt:706)
	at com.soywiz.korge.view.Views.render(Views.kt:283)
	at com.soywiz.korge.view.Views.frameUpdateAndRender-_rozLdE(Views.kt:313)
	at com.soywiz.korge.Korge$prepareViewsBase$21.invoke(Korge.kt:434)
	at com.soywiz.korge.Korge$prepareViewsBase$21.invoke(Korge.kt:38)
	at com.soywiz.korev.EventDispatcher$Mixin.dispatch(EventDispatcher.kt:51)
	at com.soywiz.korgw.GameWindow.dispatchRenderEvent(GameWindow.kt:696)
	at com.soywiz.korgw.GameWindow.frameRender(GameWindow.kt:356)
	at com.soywiz.korgw.GameWindow.frame-eeKXlv4(GameWindow.kt:333)
	at com.soywiz.korgw.GameWindow.frame-eeKXlv4$default(GameWindow.kt:332)
	at com.soywiz.korgw.GameWindow.frame(GameWindow.kt:329)
```

**Comment by LeHaine** [comment]
See file `LDtkLayerView.kt` line `123.

`val allocTiles = ntiles.nextPowerOfTwo`

This needs to be higher. The calculation must be wrong.

**Comment by LeHaine** [comment]
Need to account for allocating stacked tiles which was causing vertex count to be out of whack
